# JSONファイルを読み込む
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/buildinfo.json" JSON_STRING)

# JSON文字列からVERSIONの値を取得
string(JSON TT_VERSION_MAJOR GET "${JSON_STRING}" "TT_VERSION_MAJOR")
string(JSON TT_VERSION_MINOR GET "${JSON_STRING}" "TT_VERSION_MINOR")
string(JSON BRANCH_NAME GET "${JSON_STRING}" "BRANCH_NAME")
string(JSON DATE GET "${JSON_STRING}" "DATE")
string(JSON TIME GET "${JSON_STRING}" "TIME")

# 取得したVERSIONを表示
message("TT_VERSION_MAJOR: ${TT_VERSION_MAJOR}")
message("TT_VERSION_MINOR: ${TT_VERSION_MINOR}")
message("BRANCH_NAME: ${BRANCH_NAME}")
message("DATE: ${DATE}")
message("TIME: ${TIME}")
