name: bulid

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-teraterm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: json cmake
        run: |
          cmake -P jsontest.cmake

      - name: read json workflow yml
        id: read_buildinfo
        shell: bash
        run: |
          json_content=$(cat buildinfo.json | jq -c .)
          echo "json=$json_content" >> $GITHUB_OUTPUT
          echo "TT_VERSION_MAJOR=$(jq -r .TT_VERSION_MAJOR buildinfo.json)" >> $GITHUB_OUTPUT
          echo "TT_VERSION_MINOR=$(jq -r .TT_VERSION_MINOR buildinfo.json)" >> $GITHUB_OUTPUT
          echo "TT_VERSION_SUBSTR=$(jq -r .TT_VERSION_SUBSTR buildinfo.json)" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(jq -r .BRANCH_NAME buildinfo.json)" >> $GITHUB_OUTPUT
          echo "DATE=$(jq -r .DATE buildinfo.json)" >> $GITHUB_OUTPUT
          echo "TIME=$(jq -r .TIME buildinfo.json)" >> $GITHUB_OUTPUT

      - name: json workflow yml
        shell: bash
        run: |
          echo "TT_VERSION_MAJOR ${{ fromJson(steps.read_buildinfo.outputs.json).TT_VERSION_MAJOR }}"
          echo "TT_VERSION_MINOR ${{ fromJson(steps.read_buildinfo.outputs.json).TT_VERSION_MINOR }}"
          echo "TT_VERSION_SUBSTR ${{ fromJson(steps.read_buildinfo.outputs.json).TT_VERSION_SUBSTR }}"
          echo "BRANCH_NAME ${{ fromJson(steps.read_buildinfo.outputs.json).BRANCH_NAME }}"
          echo "DATE ${{ fromJson(steps.read_buildinfo.outputs.json).DATE }}"
          echo "TIME ${{ fromJson(steps.read_buildinfo.outputs.json).TIME }}"
          echo "TT_VERSION_MAJOR ${{ steps.read_buildinfo.outputs.TT_VERSION_MAJOR }}"
          echo "TT_VERSION_MINOR ${{ steps.read_buildinfo.outputs.TT_VERSION_MINOR }}"
