name: bulid
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 19:00 UTC(JST+0900 04:00, Note: 19+9-24=4):
    - cron:  '0 19 * * *'

env:
  NOPAUSE: 1
  REMOVE_TMP: 1
  RETENTION_DAYS: 3

jobs:
  build-teraterm:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          git clone https://github.com/TeraTermProject/teraterm.git --depth 1 --branch main
          cd teraterm
          cd buildtools
          cmake -P install_sbapplocale.cmake
          cmake -P install_innosetup.cmake
          cmake -P install_cygwin.cmake
          cd ..
          cd libs
          cmake -DCMAKE_GENERATOR="Visual Studio 17 2022" -DARCHITECTURE=arm64 -P buildall.cmake
          cd ..
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A arm64
          cmake --build . --config Release
          cmake --build . --config Release --target install
          cmake --build . --config Release --target inno_setup
          cmake --build . --config Release --target zip
