name: bulid
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 19:00 UTC(JST+0900 04:00, Note: 19+9-24=4):
    - cron:  '0 19 * * *'

env:
  NOPAUSE: 1
  REMOVE_TMP: 1
  RETENTION_DAYS: 3

jobs:
  build-teraterm:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: checkout teraterm
        run: |
          git clone https://github.com/TeraTermProject/teraterm.git --depth 1 --branch main
      - name: Restore cached libs
        id: cache-libs-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            teraterm/libs
            teraterm/buildtools
          key: cache-${{ hashFiles('teraterm/libs/*.cmake', 'teraterm/libs/*.bat', 'teraterm/buildtools/*.bat', 'teraterm/buildtools/*.bat', 'teraterm/buildtools/download/cygwin_package/https%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/setup.ini') }}
      - name: build
        run: |
          cd teraterm
          cd buildtools
          cmake -P install_sbapplocale.cmake
          cmake -P install_innosetup.cmake
          cmake -P install_cygwin.cmake
          cd ..
          cd libs
          cmake -DCMAKE_GENERATOR="Visual Studio 17 2022" -DARCHITECTURE=arm64 -P buildall.cmake
          cd ..
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A arm64
          cmake --build . --config Release
          cmake --build . --config Release --target install
          cmake --build . --config Release --target inno_setup
          cmake --build . --config Release --target zip
      - name: artifacts zip
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: |
            teraterm/build/teraterm*.zip
      - name: artifacts installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            teraterm/build/teraterm*.exe
      - name: Save libs
        id: cache-libs-save
        uses: actions/cache/save@v4
        if: steps.cache-libs-restore.outputs.cache-hit != 'true'
        with:
          path: |
            teraterm/libs
            teraterm/buildtools
          key: cache-${{ hashFiles('teraterm/libs/*.cmake', 'teraterm/libs/*.bat', 'teraterm/buildtools/*.bat', 'teraterm/buildtools/*.bat', 'teraterm/buildtools/download/cygwin_package/https%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/setup.ini') }}
